/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manel2;


import java.awt.Component;
import java.awt.Dimension;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.nio.charset.Charset;
import java.nio.charset.StandardCharsets;
import java.nio.file.Path;
import javax.imageio.ImageIO;
import javax.swing.JComponent;
import javax.swing.JFileChooser;




import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JuniorMaia
 */
public class Planilha2 extends javax.swing.JFrame {
     private static String filePath;
     private static Path caminho = null;
     private static final Charset iso_8859_1 = StandardCharsets.ISO_8859_1;
     private static int contador_arquivo = 0;
     final JFileChooser fc = new JFileChooser();

    /**
     * Creates new form Planilha2
     */
    public Planilha2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxNome = new javax.swing.JComboBox<>();
        jComboBoxLargura = new javax.swing.JComboBox<>();
        jComboBoxAltura = new javax.swing.JComboBox<>();
        jComboBoxPeitoril = new javax.swing.JComboBox<>();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jComboBoxQuantidade = new javax.swing.JComboBox<>();
        jButtonAdicionar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTMedicoes = new javax.swing.JTable();
        jButtonAlterar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxMateriais = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jButtonBaixar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(" Architect V 1.5");
        setResizable(false);

        jLabel1.setText("NOME");

        jLabel2.setText("LARGURA(cm)");

        jLabel3.setText("ALTURA(m)");

        jLabel4.setText("PEITORIL(cm)");

        jLabel5.setText("QUANTIDADE");

        jLabel6.setText("TIPO");

        jComboBoxNome.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "P-1", "P-2", "P-3", "P-4", "P-5", "P-6", "P-7", "P-8", "P-9", "P-10", "P-11", "P-12", "P-13", "P-14", "P-15", "P-16", "P-17", "P-18", "P-19", "P-20", "J-1", "J-2", "J-3", "J-4", "J-5", "J-6", "J-7", "J-8", "J-9", "J-10", "J-11", "J-12", "J-13", "J-14", "J-15", "J-16", "J-17", "J-18", "J-19", "J-20" }));

        jComboBoxLargura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0cm", "5cm", "10cm", "15cm", "20cm", "25cm", "30cm", "35cm", "40cm", "45cm", "50cm", "55cm", "60cm", "65cm", "70cm", "75cm", "80cm", "85cm", "90cm", "95cm", "100cm", "120cm", "130cm", "140cm", "150cm", "160cm", "170cm", "180cm", "190cm", "200cm", "210cm", "220cm", "230cm", "240cm", "250cm", "260cm", "270cm", "280cm", "290cm", "300cm" }));
        jComboBoxLargura.setToolTipText("");

        jComboBoxAltura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0cm", "5cm", "10cm", "15cm", "20cm", "25cm", "30cm", "35cm", "40cm", "45cm", "50cm", "55cm", "60cm", "65cm", "70cm", "75cm", "80cm", "85cm", "90cm", "95cm", "100cm", "120cm", "130cm", "140cm", "150cm", "160cm", "170cm", "180cm", "190cm", "200cm", "210cm", "220cm", "230cm", "240cm", "250cm", "260cm", "270cm", "280cm", "290cm", "300cm" }));

        jComboBoxPeitoril.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0cm", "5cm", "10cm", "15cm", "20cm", "25cm", "30cm", "35cm", "40cm", "45cm", "50cm", "55cm", "60cm", "65cm", "70cm", "75cm", "80cm", "85cm", "90cm", "95cm", "100cm", "120cm", "130cm", "140cm", "150cm", "160cm", "170cm", "180cm", "190cm", "200cm", "210cm", "220cm", "230cm", "240cm", "250cm", "260cm", "270cm", "280cm", "290cm", "300cm" }));

        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Correr", "Correr 2 folhas", "Correr 3 folhas", "Correr 4 folhas", "Giro para direita", "Giro para esquerda", "Basculante", "Rôlo" }));
        jComboBoxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoActionPerformed(evt);
            }
        });

        jComboBoxQuantidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50" }));

        jButtonAdicionar.setText("ADICIONAR");
        jButtonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("EXCLUIR");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jTMedicoes.setAutoCreateRowSorter(true);
        jTMedicoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"                   NOME", "            LARGURA", "                 ALTURA", "               PEITORIL", "            QUANTIDADE", "                    TIPO", "              MATERIAIS"}
            },
            new String [] {
                "NOME", "LARGURA(m)", "ALTURA", "PEITORIL", "QUANTIDADE", "TIPO", "MATERIAIS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTMedicoes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTMedicoes.setName(""); // NOI18N
        jTMedicoes.setRowSelectionAllowed(false);
        jTMedicoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTMedicoesMouseClicked(evt);
            }
        });
        jTMedicoes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTMedicoesKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTMedicoes);
        jTMedicoes.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jButtonAlterar.setText("ALTERAR");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jLabel7.setText("MATERIAIS");

        jComboBoxMateriais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Madeira", "Alumínio", "Vidro", "Alumínio/vidro", "Madeira/vidro", "Ferro Compensado", "MDF", "Inox" }));

        jLabel8.setText("JM SOFTWARE");

        jButtonBaixar.setText("BAIXAR");
        jButtonBaixar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBaixarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jButtonAdicionar)
                .addGap(133, 133, 133)
                .addComponent(jButtonExcluir)
                .addGap(71, 71, 71)
                .addComponent(jLabel8)
                .addGap(58, 58, 58)
                .addComponent(jButtonAlterar)
                .addGap(173, 173, 173)
                .addComponent(jButtonBaixar))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1024, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jComboBoxNome, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBoxLargura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxPeitoril, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)
                        .addComponent(jComboBoxQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jComboBoxMateriais, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(82, 82, 82)
                        .addComponent(jLabel5)
                        .addGap(61, 61, 61)
                        .addComponent(jLabel6)
                        .addGap(122, 122, 122)
                        .addComponent(jLabel7))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxLargura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxPeitoril, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxMateriais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAdicionar)
                            .addComponent(jButtonExcluir)
                            .addComponent(jButtonAlterar)
                            .addComponent(jButtonBaixar))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipoActionPerformed

    private void jTMedicoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTMedicoesMouseClicked
        
       if(jTMedicoes.getSelectedRow() != -1){
           
            jComboBoxNome.setSelectedItem(jTMedicoes.getValueAt(jTMedicoes.getSelectedRow(), 0));
            jComboBoxLargura.setSelectedItem(jTMedicoes.getValueAt(jTMedicoes.getSelectedRow(), 1));
            jComboBoxAltura.setSelectedItem(jTMedicoes.getValueAt(jTMedicoes.getSelectedRow(), 2));
            jComboBoxPeitoril.setSelectedItem(jTMedicoes.getValueAt(jTMedicoes.getSelectedRow(), 3));
            jComboBoxQuantidade.setSelectedItem(jTMedicoes.getValueAt(jTMedicoes.getSelectedRow(), 4));
            jComboBoxTipo.setSelectedItem(jTMedicoes.getValueAt(jTMedicoes.getSelectedRow(), 5));
            jComboBoxMateriais.setSelectedItem(jTMedicoes.getValueAt(jTMedicoes.getSelectedRow(), 6));
        }else{
            JOptionPane.showMessageDialog(null, "SELECIONE ITEM A SER ALTERADO!");
        }
        
    }//GEN-LAST:event_jTMedicoesMouseClicked

    private void jButtonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarActionPerformed
    
        DefaultTableModel dtmMedicoes = (DefaultTableModel) jTMedicoes.getModel();
        Object[] dados = {jComboBoxNome.getSelectedItem(),jComboBoxLargura.getSelectedItem(),
                          jComboBoxAltura.getSelectedItem(), jComboBoxPeitoril.getSelectedItem(),
                          jComboBoxQuantidade.getSelectedItem(), jComboBoxTipo.getSelectedItem(),
                          jComboBoxMateriais.getSelectedItem()
        };
        
        dtmMedicoes.addRow(dados);
        
        
        
    }//GEN-LAST:event_jButtonAdicionarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        //jTMedicoes.getSelectedRow();
        
        if(jTMedicoes.getSelectedRow() != 0){
        
            int resposta =  JOptionPane.showConfirmDialog(null, "TEM CERTEZA QUE QUER EXCLUIR?","ALERTA", JOptionPane.OK_CANCEL_OPTION);
        
                        if(resposta == JOptionPane.YES_OPTION){
       
            
                                 DefaultTableModel dtmMedicoes = (DefaultTableModel) jTMedicoes.getModel();
                                dtmMedicoes.removeRow(jTMedicoes.getSelectedRow());
                        }else if(resposta == JOptionPane.NO_OPTION){
                                return;
                                                                    }   
                
        }else{   
        
                JOptionPane.showMessageDialog(null, "SELECIONE UM PRODUTO PARA EXCLUIR.", "ALERTA!", JOptionPane.ERROR_MESSAGE);
                    
            //JOptionPane.showMessageDialog(null, "SELECIONE UM PRODUTO PARA EX 
        }
        
            
               
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jTMedicoesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTMedicoesKeyReleased
       if(jTMedicoes.getSelectedRow() != -1){
            jComboBoxNome.setSelectedItem(jTMedicoes.getValueAt(jTMedicoes.getSelectedRow(), 0));
            jComboBoxLargura.setSelectedItem(jTMedicoes.getValueAt(jTMedicoes.getSelectedRow(), 1));
            jComboBoxAltura.setSelectedItem(jTMedicoes.getValueAt(jTMedicoes.getSelectedRow(), 2));
            jComboBoxPeitoril.setSelectedItem(jTMedicoes.getValueAt(jTMedicoes.getSelectedRow(), 3));
            jComboBoxQuantidade.setSelectedItem(jTMedicoes.getValueAt(jTMedicoes.getSelectedRow(), 4));
            jComboBoxTipo.setSelectedItem(jTMedicoes.getValueAt(jTMedicoes.getSelectedRow(), 5));
            jComboBoxMateriais.setSelectedItem(jTMedicoes.getValueAt(jTMedicoes.getSelectedRow(), 6));
            
            JOptionPane.showMessageDialog(this, "ITEM ALTERADO COM SUCESSO!");
        }else{
            JOptionPane.showMessageDialog(null, "SELECIONE ITEM A SER ALTERADO!");
        }
        
    }//GEN-LAST:event_jTMedicoesKeyReleased

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        
        
        if(jTMedicoes.getSelectedRow() != 0){
             jTMedicoes.setValueAt(jComboBoxNome.getSelectedItem(), jTMedicoes.getSelectedRow(), 0);
             jTMedicoes.setValueAt(jComboBoxLargura.getSelectedItem(), jTMedicoes.getSelectedRow(), 1);
             jTMedicoes.setValueAt(jComboBoxAltura.getSelectedItem(), jTMedicoes.getSelectedRow(), 2);
             jTMedicoes.setValueAt(jComboBoxPeitoril.getSelectedItem(), jTMedicoes.getSelectedRow(), 3);
             jTMedicoes.setValueAt(jComboBoxQuantidade.getSelectedItem(), jTMedicoes.getSelectedRow(), 4);
             jTMedicoes.setValueAt(jComboBoxTipo.getSelectedItem(), jTMedicoes.getSelectedRow(), 5);
             jTMedicoes.setValueAt(jComboBoxMateriais.getSelectedItem(), jTMedicoes.getSelectedRow(), 6);
             
             
             JOptionPane.showMessageDialog(null, "ITEM ALTERADO COM SUCESSO!", "ALTERADO!", JOptionPane.INFORMATION_MESSAGE);
            
         
         }else{
                JOptionPane.showMessageDialog(null, "SELECIONE UM PRODUTO PARA ALTERAR.", "ALERTA!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonBaixarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBaixarActionPerformed
          
       
        
           if(jTMedicoes.getRowCount() == 1 ){  
               JOptionPane.showMessageDialog(null, "ERRO AO BAIXAR, PREENCHA A TABELA!", "ERRO!", JOptionPane.ERROR_MESSAGE);
            
           }else{
            
   
               caminhoSalvar();
               
               
              

             
           
                    }
             
    }//GEN-LAST:event_jButtonBaixarActionPerformed
      
  
    
    private void salvarImagem(JComponent componente, String formato, File arquivo) {
    try {      
        Dimension tamanho = componente.getSize();
        BufferedImage imagem = new BufferedImage(tamanho.width, tamanho.height, BufferedImage.TYPE_INT_RGB);
        componente.paint(imagem.getGraphics());
        boolean write = ImageIO.write(imagem, formato, arquivo);
    } catch (IOException e) {
        e.printStackTrace();
    }   
    
}
    
    public void caminhoSalvar(){
       JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Salvar");
    FileNameExtensionFilter filter = new FileNameExtensionFilter("Arquivos jpg (*.jpg)", "jpg");
    fileChooser.addChoosableFileFilter(filter);
    fileChooser.setFileFilter(filter);
    int option = fileChooser.showSaveDialog(this);
    if (option == JFileChooser.APPROVE_OPTION) {
        File arquivo = fileChooser.getSelectedFile();
        if (!arquivo.getName().toLowerCase().endsWith(".jpg")) {
            arquivo = new File(arquivo.getParent(), arquivo.getName() + ".jpg");
        }
        salvarImagem(jTMedicoes, "jpg", arquivo);
        JOptionPane.showMessageDialog(this, "INFORMAÇÃO BAIXADA COM SUCESSO!", "BAIXADO!", JOptionPane.INFORMATION_MESSAGE);
       
    
    }

        

    }
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
     

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                
                new Planilha2().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicionar;
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonBaixar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JComboBox<String> jComboBoxAltura;
    private javax.swing.JComboBox<String> jComboBoxLargura;
    private javax.swing.JComboBox<String> jComboBoxMateriais;
    private javax.swing.JComboBox<String> jComboBoxNome;
    private javax.swing.JComboBox<String> jComboBoxPeitoril;
    private javax.swing.JComboBox<String> jComboBoxQuantidade;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTMedicoes;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
